services:
  - type: web
    name: StockLineBot
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=${PORT:8000}
    envVars:
    - key: PYTHON_VERSION
      value: 3.9.12
    - key: CHANNEL_ACCESS_TOKEN
      sync: false
    - key: CHANNEL_SECRET
      sync: false
    - key: OPENAI_API_KEY
      sync: false
    - key: SERPAPI_API_KEY
    sync: false